# Generated by Django 4.0.5 on 2022-07-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voen_chas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vvt',
            options={'managed': False},
        ),
    ]
