# Generated by Django 4.0.5 on 2022-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voen_chas', '0002_alter_vvt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiskovieChasti',
            fields=[
                ('id_voiskovie_chasti', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Название')),
                ('gorod', models.CharField(db_column='Gorod', max_length=50, verbose_name='Город')),
                ('rgk', models.CharField(db_column='RGK', max_length=100, verbose_name='РГК')),
                ('rod_voiska', models.CharField(db_column='Rod_voiska', max_length=50, verbose_name='Род войска')),
            ],
            options={
                'verbose_name': 'Войсковые части',
                'verbose_name_plural': 'Войсковые части',
                'db_table': 'voiskovie_chasti',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vvt',
            options={'managed': False, 'verbose_name': 'Обьекты ВВТ', 'verbose_name_plural': 'Обьекты ВВТ'},
        ),
    ]
