from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('register/', views.registerPage, name='register'),
    # path('registration/', views.registration, name='registration'),
    path('login/', views.loginPage, name='login'), 
    path('logout/', views.logoutUser, name='logout'),
    path('main/', views.main, name='main'),
    path('statistics/', views.statistics, name='statistics'), 
    path('nuo/', views.nuo, name='nuo'), 

    path("changeTO1/<int:id>", views.changeTO1),
    path("changeTO2/<int:id>", views.changeTO2),

    path('pasport/', views.pasp, name='pasport'), 
    path('pasport_ckp/', views.pasport_ckp, name='pasport_ckp'), 
    path('pasport_gus/', views.pasport_gus, name='pasport_gus'), 
    path('pasport_domr/', views.pasport_domr, name='pasport_domr'), 
    path('pasport_gut/', views.pasport_gut, name='pasport_gut'), 
    path('pasport_gsh/', views.pasport_gsh, name='pasport_gsh'), 
    path('pasport_dvon/', views.pasport_dvon, name='pasport_dvon'), 
    path('pasport_guvp/', views.pasport_guvp, name='pasport_guvp'), 
    path('pasport_vms/', views.pasport_vms, name='pasport_vms'), 
    path('pasport_svo/', views.pasport_svo, name='pasport_svo'), 
    path('pasport_zapad/', views.pasport_zapad, name='pasport_zapad'), 
    path('pasport_dshv/', views.pasport_dshv, name='pasport_dshv'), 
    path('pasport_astana/', views.pasport_astana, name='pasport_astana'), 
    path('pasport_vostok/', views.pasport_vostok, name='pasport_vostok'), 
    path('pasport_chnp/', views.pasport_chnp, name='pasport_chnp'), 
    path('pasport_yug/', views.pasport_yug, name='pasport_yug'), 
    path('pasport_untiv/', views.pasport_untiv, name='pasport_untiv'), 
    path('pasport_gusv/', views.pasport_gusv, name='pasport_gusv'), 
    path('pasport_grau/', views.pasport_grau, name='pasport_grau'), 
    path('pasport_gurv/', views.pasport_gurv, name='pasport_gurv'), 
    path('pasport_14/', views.pasport_14, name='pasport_14'), 
    path('pasport_guv/', views.pasport_guv, name='pasport_guv'), 
    path('ckp/', views.ckp),
    path('gus/', views.gus),
    path('obshi/<int:id>', views.obshi, name='obshi'),
    path('domr/', views.domr),
    path('gut/', views.gut),
    path('gsh/', views.gsh),
    path('dkivn/', views.dkivn),
    path('guvp/', views.guvp),
    path('vms/', views.vms),
    path('svo/', views.svo),
    path('suhop_zapad/', views.suhop_zapad),
    path('suhop_dshv/', views.suhop_dshv),
    path('suhop_astana/', views.suhop_astana),
    path('suhop_vostok/', views.suhop_vostok),
    path('chnp_sv/', views.chnp_sv),
    path('suhop_yug/', views.suhop_yug),
    path('chnp_untiv/', views.chnp_untiv),
    path('gusv/', views.gusv),
    path('grau/', views.grau),
    path('gurv/', views.gurv),
    path('rv14/', views.rv14),
    path('guv/', views.guv),

    path('gruppa_eks/', views.eksplu),
    path('sort_po_category/', views.category),
    path('sort_po_godam/', views.godam),
    path('gruppa_eks_nuo/', views.eksplu_nuo),
    path('sort_po_category_nuo/', views.category_nuo),
    path('sort_po_godam_nuo/', views.godam_nuo),

    path('carDetails/<int:id>', views.carDetails ,name='carDetails'),
    path('carDetailsRK/<int:id>', views.carDetailsRK ,name='carDetailsRK'),
    path('perechen_gorodov/', views.perechen_gorodov ,name='perechen_gorodov'),

    path('gorod_abai/', views.gorod_abai ,name='gorod_abai'),
    path('gorod_aktau/', views.gorod_aktau ,name='gorod_aktau'),
    path('gorod_aktobe/', views.gorod_aktobe ,name='gorod_aktobe'),
    path('gorod_almaty/', views.gorod_almaty ,name='gorod_almaty'),
    path('gorod_arys/', views.gorod_arys ,name='gorod_arys'),
    path('gorod_astana/', views.gorod_astana ,name='gorod_astana'),
    path('gorod_atyrau/', views.gorod_atyrau ,name='gorod_atyrau'),
    path('gorod_ayagoz/', views.gorod_ayagoz ,name='gorod_ayagoz'),
    path('gorod_balhash/', views.gorod_balhash ,name='gorod_balhash'),
    path('gorod_visv/', views.gorod_visv ,name='gorod_visv'),
    path('gorod_zharkent/', views.gorod_zharkent ,name='gorod_zharkent'),
    path('gorod_zhezkazgan/', views.gorod_zhezkazgan ,name='gorod_zhezkazgan'),
    path('gorod_kapshagai/', views.gorod_kapshagai ,name='gorod_kapshagai'),
    path('gorod_karaganda/', views.gorod_karaganda ,name='gorod_karaganda'),
    path('gorod_kostanai/', views.gorod_kostanai ,name='gorod_kostanai'),
    path('gorod_kizilorda/', views.gorod_kizilorda ,name='gorod_kizilorda'),
    path('gorod_priozersk/', views.gorod_priozersk ,name='gorod_priozersk'),
    path('gorod_saran/', views.gorod_saran ,name='gorod_saran'),
    path('gorod_saryozek/', views.gorod_saryozek ,name='gorod_saryozek'),
    path('gorod_semey/', views.gorod_semey ,name='gorod_semey'),
    path('gorod_seribransk/', views.gorod_seribransk ,name='gorod_seribransk'),
    path('gorod_spask/', views.gorod_spask ,name='gorod_spask'),
    path('gorod_taldykorgan/', views.gorod_taldykorgan ,name='gorod_taldykorgan'),
    path('gorod_taraz/', views.gorod_taraz ,name='gorod_taraz'),
    path('gorod_temirtau/', views.gorod_temirtau ,name='gorod_temirtau'),
    path('gorod_ustkamenogorsk/', views.gorod_ustkamenogorsk ,name='gorod_ustkamenogorsk'),
    path('gorod_usharal/', views.gorod_usharal ,name='gorod_usharal'),
    path('gorod_shimkent/', views.gorod_shimkent ,name='gorod_shimkent'),
    path('gorod_shuchinsk/', views.gorod_shuchinsk ,name='gorod_shuchinsk'),
    path('gorod_akkol/', views.gorod_akkol ,name='gorod_akkol'),
    path('gorod_akmol/', views.gorod_akmol ,name='gorod_akmol'),
    path('gorod_beineu/', views.gorod_beineu ,name='gorod_beineu'),
    path('gorod_boroldai/', views.gorod_boroldai ,name='gorod_boroldai'),
    path('gorod_burni/', views.gorod_burni ,name='gorod_burni'),
    path('gorod_burunbai/', views.gorod_burunbai ,name='gorod_burunbai'),
    path('gorod_zhangiztobe/', views.gorod_zhangiztobe ,name='gorod_zhangiztobe'),
    path('gorod_zhetigen/', views.gorod_zhetigen ,name='gorod_zhetigen'),
    path('gorod_zhibekzholy/', views.gorod_zhibekzholy ,name='gorod_zhibekzholy'),
    path('gorod_kulan/', views.gorod_kulan ,name='gorod_kulan'),
    path('gorod_merke/', views.gorod_merke ,name='gorod_merke'),
    path('gorod_ushtobe/', views.gorod_ushtobe ,name='gorod_ushtobe'),
    path('gorod_shamalgan/', views.gorod_shamalgan ,name='gorod_shamalgan'),
    path('gorod_gvardeiski/', views.gorod_gvardeiski ,name='gorod_gvardeiski'),
    path('gorod_sarikemir/', views.gorod_sarikemir ,name='gorod_sarikemir'),
    path('gorod_lugovoi/', views.gorod_lugovoi ,name='gorod_lugovoi'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
