# Generated by Django 4.0.5 on 2022-07-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akb',
            fields=[
                ('akb_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Наименование')),
                ('obiekti_vvt', models.CharField(db_column='Obiekti_vvt', max_length=255, verbose_name='Обьекты ВВТ')),
                ('kem_vidano', models.CharField(blank=True, db_column='Kem_vidano', max_length=50, null=True, verbose_name='Кем выдано')),
                ('kogda_vidano', models.DateField(blank=True, db_column='Kogda_vidano', null=True, verbose_name='Когда выдано')),
                ('spisanie', models.CharField(blank=True, db_column='Spisanie', max_length=50, null=True, verbose_name='Списание')),
            ],
            options={
                'verbose_name': 'АКБ',
                'verbose_name_plural': 'АКБ',
                'db_table': 'akb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avtoshini',
            fields=[
                ('avtoshin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Наименование')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True, verbose_name='Тип')),
                ('obiekti_vvt', models.CharField(db_column='Obiekti_vvt', max_length=255, verbose_name='Обьекты ВВТ')),
                ('kem_vidano', models.CharField(blank=True, db_column='Kem_vidano', max_length=50, null=True, verbose_name='Кем выдано')),
                ('kogda_vidano', models.DateField(blank=True, null=True, verbose_name='Когда выдано')),
                ('spisanie', models.CharField(blank=True, db_column='Spisanie', max_length=50, null=True, verbose_name='Списание')),
            ],
            options={
                'verbose_name': 'Автошины',
                'verbose_name_plural': 'Автошины',
                'db_table': 'avtoshini',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goroda',
            fields=[
                ('gorod_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Города',
                'db_table': 'goroda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObiektiVvt',
            fields=[
                ('id_vvt', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_vvt', models.CharField(db_column='Marka_VVT', max_length=50, verbose_name='Марка ВВТ')),
                ('voenni_reg_nomer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Военный рег номер')),
                ('god_vipuska', models.DateField(blank=True, null=True, verbose_name='Год выпуска')),
                ('field_shassi', models.IntegerField(blank=True, db_column='№_shassi', null=True, verbose_name='№ шасси')),
                ('field_dvigatelia', models.IntegerField(blank=True, db_column='№_dvigatelia', null=True, verbose_name='№ двигателя')),
                ('field_pasport_formulara', models.IntegerField(blank=True, db_column='№_pasport_formulara', null=True, verbose_name='№ Паспорт формуляра')),
                ('rgk', models.CharField(db_column='RGK', max_length=100, verbose_name='РГК')),
                ('gorod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('gruppa_ekspluatacii', models.CharField(max_length=50, verbose_name='группа эксплуатаций')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('norma_rashoda', models.CharField(blank=True, max_length=50, null=True, verbose_name='Норма расхода')),
                ('type_of_mark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип марки')),
                ('rod_voiska', models.CharField(max_length=50, verbose_name='Род войска')),
                ('voiskovaia_chast', models.CharField(max_length=50, verbose_name='Войсковая часть')),
                ('podrazdelenia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подразделения')),
                ('tp', models.IntegerField(blank=True, db_column='TP', null=True, verbose_name='ТР')),
                ('cp', models.IntegerField(blank=True, db_column='CP', null=True, verbose_name='СР')),
                ('kp', models.IntegerField(blank=True, db_column='KP', null=True, verbose_name='КР')),
                ('spisanie', models.CharField(blank=True, db_column='Spisanie', max_length=50, null=True, verbose_name='Списание')),
                ('sostoianie', models.CharField(blank=True, db_column='Sostoianie', max_length=255, null=True, verbose_name='Состояние')),
                ('need', models.IntegerField(blank=True, db_column='Need', null=True, verbose_name='Потребность')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='Имеется')),
                ('shortage', models.IntegerField(blank=True, null=True, verbose_name='Некомплект')),
                ('excess', models.IntegerField(blank=True, null=True, verbose_name='Излишествует')),
                ('verification', models.CharField(max_length=50, verbose_name='Проверка')),
            ],
            options={
                'verbose_name': 'Обьекты ВВТ',
                'verbose_name_plural': 'Обьекты ВВТ',
                'db_table': 'obiekti_vvt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peremeshenie',
            fields=[
                ('premesh_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('field_prikaza_nomer_date_field', models.IntegerField(db_column='№_prikaza(nomer, date)', verbose_name='№ приказа')),
                ('obiekti_vvt', models.CharField(db_column='Obiekti_vvt', max_length=50, verbose_name='Обьекты ВВТ')),
                ('voiskovaia_chast', models.CharField(db_column='Voiskovaia_chast', max_length=50, verbose_name='Войсковая часть')),
                ('podrazdelenia', models.CharField(db_column='Podrazdelenia', max_length=50, verbose_name='Подразделения')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещение',
                'db_table': 'peremeshenie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podrazdelenia',
            fields=[
                ('id_podrazdelenia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подразделения',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'podrazdelenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoiskovieChasti',
            fields=[
                ('id_voiskovie_chasti', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Название')),
                ('gorod', models.CharField(db_column='Gorod', max_length=50, verbose_name='Город')),
                ('rgk', models.CharField(db_column='RGK', max_length=100, verbose_name='РГК')),
                ('rod_voiska', models.CharField(db_column='Rod_voiska', max_length=50, verbose_name='Род войска')),
            ],
            options={
                'verbose_name': 'Войсковые части',
                'verbose_name_plural': 'Войсковые части',
                'db_table': 'voiskovie_chasti',
                'managed': False,
            },
        ),
    ]
