# Generated by Django 4.0.6 on 2022-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkbNew',
            fields=[
                ('akb_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id АКБ')),
                ('type_akb', models.CharField(max_length=50, verbose_name='Тип шины')),
                ('kolichestvo_akb', models.IntegerField(verbose_name='Количество АКБ')),
                ('kev_vidano', models.CharField(max_length=50, verbose_name='Кем выдано')),
                ('field_nariad_kogda_vidano', models.CharField(db_column='№_nariad_kogda_vidano', max_length=50, verbose_name='№ наряда и когда выдано')),
                ('srok_sluzhbi', models.IntegerField(verbose_name='Срок службы')),
                ('data_ustanovki_akb', models.DateField(verbose_name='Дата установки АКБ')),
                ('data_spisania_akb_po_godam', models.DateField(blank=True, null=True, verbose_name='Дата списания АКБ по годам')),
                ('srok_sluzhbi_v_km_do_spisania', models.IntegerField(verbose_name='Дата списания АКБ по годам')),
                ('january', models.IntegerField(blank=True, db_column='January', null=True, verbose_name='Январь')),
                ('february', models.IntegerField(blank=True, db_column='February', null=True, verbose_name='Февраль')),
                ('march', models.IntegerField(blank=True, db_column='March', null=True, verbose_name='Март')),
                ('april', models.IntegerField(blank=True, db_column='April', null=True, verbose_name='Апрель')),
                ('may', models.IntegerField(blank=True, db_column='May', null=True, verbose_name='Май')),
                ('june', models.IntegerField(blank=True, db_column='June', null=True, verbose_name='Июль')),
                ('july', models.IntegerField(blank=True, db_column='July', null=True, verbose_name='Июнь')),
                ('august', models.IntegerField(blank=True, db_column='August', null=True, verbose_name='Август')),
                ('september', models.IntegerField(blank=True, db_column='September', null=True, verbose_name='Сентябрь')),
                ('october', models.IntegerField(blank=True, db_column='October', null=True, verbose_name='Октябрь')),
                ('november', models.IntegerField(blank=True, db_column='November', null=True, verbose_name='Ноябрь')),
                ('december', models.IntegerField(blank=True, db_column='December', null=True, verbose_name='Декабрь')),
                ('proideno_km_from_beginning', models.IntegerField(blank=True, null=True, verbose_name=' Пройдено км с момента установки АКБ')),
                ('ostalos_km_do_spisania', models.IntegerField(blank=True, null=True, verbose_name='Осталось км. до списания')),
            ],
            options={
                'verbose_name': 'АКБ новый',
                'verbose_name_plural': 'АКБ новый',
                'db_table': 'akb_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvtoshiniNew',
            fields=[
                ('id_shin', models.AutoField(primary_key=True, serialize=False, verbose_name='id шин')),
                ('type_shin', models.CharField(max_length=50, verbose_name='Тип шины')),
                ('razmer_shin', models.CharField(max_length=50, verbose_name='Размер шин ')),
                ('kolichestvo_shin', models.CharField(max_length=50, verbose_name='Количество шин ')),
                ('kem_vidano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кем выдано ')),
                ('field_nariad_kogda_vidano', models.CharField(blank=True, db_column='№_nariad_kogda_vidano', max_length=50, null=True, verbose_name='№ наряда и когда выданы шины')),
                ('data_ustanovki_shini', models.CharField(max_length=50, verbose_name=' Дата установки шин')),
                ('srok_sluzhbi_v_km', models.IntegerField(verbose_name='Срок службы в км. до списания шин')),
                ('january', models.IntegerField(blank=True, db_column='January', null=True, verbose_name='Январь')),
                ('february', models.IntegerField(blank=True, db_column='February', null=True, verbose_name='Февраль')),
                ('march', models.IntegerField(blank=True, db_column='March', null=True, verbose_name='Март')),
                ('april', models.IntegerField(blank=True, db_column='April', null=True, verbose_name='Апрель')),
                ('may', models.IntegerField(blank=True, db_column='May', null=True, verbose_name='Май')),
                ('june', models.IntegerField(blank=True, db_column='June', null=True, verbose_name='Июнь')),
                ('july', models.IntegerField(blank=True, db_column='July', null=True, verbose_name='Июль')),
                ('august', models.IntegerField(blank=True, db_column='August', null=True, verbose_name='Август')),
                ('september', models.IntegerField(blank=True, db_column='September', null=True, verbose_name='Сентябрь')),
                ('october', models.IntegerField(blank=True, db_column='October', null=True, verbose_name='Октябрь')),
                ('november', models.IntegerField(blank=True, db_column='November', null=True, verbose_name='Ноябрь')),
                ('december', models.IntegerField(blank=True, db_column='December', null=True, verbose_name='Декабрь')),
                ('proideno_km_from_beginning', models.IntegerField(blank=True, null=True, verbose_name='Пройдено киллометров с момента установки шин')),
                ('proideno_km_from_beginning_uchetom_zapasnogo', models.IntegerField(blank=True, null=True, verbose_name='Пройдено км с момента установки с учетом запасного колеса')),
                ('ostalos_km_do_spisania', models.IntegerField(blank=True, null=True, verbose_name=' Осталось киллометров до списания (с учетом запасного колеса)')),
            ],
            options={
                'verbose_name': 'Автошины новые',
                'verbose_name_plural': 'Автошины новые',
                'db_table': 'avtoshini_new',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'managed': False, 'verbose_name': 'NUO', 'verbose_name_plural': 'NUO'},
        ),
    ]
