# Generated by Django 4.0.6 on 2022-09-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_akbnew_avtoshininew_alter_main_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'managed': False, 'verbose_name': 'Национальный Универ Обороны', 'verbose_name_plural': 'Национальный Универ Обороны'},
        ),
    ]
