# Generated by Django 4.0.6 on 2022-09-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AkbNew',
        ),
    ]
