# Generated by Django 4.0.6 on 2022-10-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_akbnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtoshininew',
            options={'managed': False, 'verbose_name': 'Автошины НУО', 'verbose_name_plural': 'Автошины НУО'},
        ),
        migrations.AlterModelOptions(
            name='obiektivvt',
            options={'managed': False, 'verbose_name': 'Общий ВВТ', 'verbose_name_plural': 'Общий ВВТ'},
        ),
        migrations.AlterModelOptions(
            name='vvt',
            options={'managed': False, 'verbose_name': 'Обьекты ВВТ индивидуально', 'verbose_name_plural': 'Обьекты ВВТ индивидуально'},
        ),
    ]
