# Generated by Django 4.1.3 on 2022-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_avtoshininew_options_alter_obiektivvt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'managed': False, 'verbose_name': 'Национальный Университет Обороны', 'verbose_name_plural': 'Национальный Университет Обороны'},
        ),
        migrations.AlterModelOptions(
            name='obiektivvt',
            options={'managed': False, 'verbose_name': 'Общие данные АТ', 'verbose_name_plural': 'Общие данные АТ'},
        ),
        migrations.AlterModelOptions(
            name='vvt',
            options={'managed': False, 'verbose_name': 'Объекты АТ индивидуально', 'verbose_name_plural': 'Объекты АТ индивидуально'},
        ),
    ]
